# Generated by Django 4.2.1 on 2023-05-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Es', 'Español'), ('En', 'Inglés')], max_length=100)),
                ('started', models.DateField()),
                ('ended', models.DateField(blank=True, null=True)),
                ('degree', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='education')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='ProjectsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='proyects')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Projects Images',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Es', 'Español'), ('En', 'Inglés')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='skills/logos')),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('is_soft_skill', models.BooleanField(default=False)),
                ('learning', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Es', 'Español'), ('En', 'Inglés')], max_length=100)),
                ('started', models.DateField()),
                ('ended', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='proyects/logos')),
                ('url_back', models.CharField(blank=True, max_length=225, null=True)),
                ('url_front', models.CharField(blank=True, max_length=225, null=True)),
                ('url_deploy', models.CharField(blank=True, max_length=225, null=True)),
                ('images', models.ManyToManyField(blank=True, to='data.projectsimages')),
                ('technologies', models.ManyToManyField(blank=True, to='data.skills')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Es', 'Español'), ('En', 'Inglés')], max_length=100)),
                ('started', models.DateField()),
                ('ended', models.DateField(blank=True, null=True)),
                ('company', models.CharField(max_length=225)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies')),
                ('position', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('technologies', models.ManyToManyField(to='data.skills')),
            ],
            options={
                'verbose_name': 'Job Experience',
                'verbose_name_plural': 'Job Experiences',
            },
        ),
    ]
